### ISSUE TITLE
lucidaot option doesn't work with system fonts 

### ISSUE THREAD

**Issue by fintelkai** [semprag/tex#20]
When the Lucida OT fonts are in a local ./fonts directory, typesetting `basic.tex` (changed to `lucidaot` option) with XeLaTeX succeeds. But when the fonts are either in `/Library/Fonts` or in `~/Library/Fonts`, the following error happens:

````
(/usr/local/texlive/2018/texmf-dist/tex/latex/unicode-math/unicode-math-table.t
ex)))kpathsea:make_tex: Invalid filename `[LucidaBrightOT.otf]/OT', contains '['


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "LucidaBrightOT" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.107     BoldItalicFont=*-DemiItalic]
````

FWIW, typesetting `lucidaot-sys-example.tex` with XeLaTeX works just fine, so something in `sp.cls` is not letting `fontspec` find the system fonts.

**Comment by fintelkai** [comment]
I think the problem is that `LucidaBrightOT` is the wrong name for the system font to be found. As in `lucidaot-sys-example.tex`, the font should be called `Lucida Bright OT`, with spaces, because that's what installing them through FontBook results in. The following changed lines in `sp.cls` solve the problem for me:

````latex
  \defaultfontfeatures{Ligatures=TeX,Scale=0.9}
  \IfFileExists{./fonts/LucidaBrightOT.otf}{
    % look for Lucida font files in 'fonts' directory if it exists
    \defaultfontfeatures+{Path=./fonts/,Extension=.otf}
    \ClassInfo{sp.cls}{Loading LucidaOT files from local ./fonts/ directory; using globally-installed fonts is preferred}
  }{}
  \setmainfont{Lucida Bright OT}
  \setsansfont{Lucida Sans OT}
  \setmonofont{Lucida Sans Typewriter OT}
  \setmathfont{Lucida Bright Math OT}
  \setmathfont{Lucida Bright Math OT Demibold}[version=bold]
````

I won't push this change until this has been validated.

**Comment by chbrown** [comment]
It's been a while since I was debugging these OT vs. texmf, when I made those decisions, so your experience might be fresher. Below are my results of picking this back up.

I wasn't using Font Book, then, for global installs, but the manual `cp` call in https://github.com/semprag/lucida#opentype -- which simply copies the files to `$TEXMFHOME/fonts/opentype/*.otf`.

I still have the fonts globally installed that way. And, referring to the names with spaces, as in your snippet of changes, breaks.

As a test, I just removed those files and installed all the OT versions with Font Book. Now neither "LucidaBrightOT" nor "Lucida Bright OT" work. The fonts are displayed in Font Book, and the files seem to have gotten installed properly:

     42396 Jan 14  2012 ~/Library/Fonts/LucidaBlackletterOT.otf
    184476 Mar  6  2012 ~/Library/Fonts/LucidaBrightMathOT-Demi.otf
    391852 Mar  7  2012 ~/Library/Fonts/LucidaBrightMathOT.otf
     60140 Jan 14  2012 ~/Library/Fonts/LucidaBrightOT-Demi.otf
     43884 Jan 14  2012 ~/Library/Fonts/LucidaBrightOT-DemiItalic.otf
     44240 Jan 14  2012 ~/Library/Fonts/LucidaBrightOT-Italic.otf
     95764 Jan 14  2012 ~/Library/Fonts/LucidaBrightOT.otf
     31228 Jan 14  2012 ~/Library/Fonts/LucidaCalligraphyOT.otf
     43012 Jan 14  2012 ~/Library/Fonts/LucidaHandwritingOT.otf
     35100 Jan 14  2012 ~/Library/Fonts/LucidaSansOT-Demi.otf
     34992 Jan 14  2012 ~/Library/Fonts/LucidaSansOT-DemiItalic.otf
     34404 Jan 14  2012 ~/Library/Fonts/LucidaSansOT-Italic.otf
     35392 Jan 14  2012 ~/Library/Fonts/LucidaSansOT.otf
     35256 Jan 14  2012 ~/Library/Fonts/LucidaSansTypewriterOT-Bold.otf
     33228 Jan 14  2012 ~/Library/Fonts/LucidaSansTypewriterOT-BoldOblique.otf
     33644 Jan 14  2012 ~/Library/Fonts/LucidaSansTypewriterOT-Oblique.otf
     34784 Jan 14  2012 ~/Library/Fonts/LucidaSansTypewriterOT.otf

Did you have to do anything else to have your latex distribution look in Font Book's directories?

My macOS (Sierra) is a minor version behind the current release, though I doubt that's relevant.

Maybe we should rename the font files to their eventual / proper names, despite the spaces?

P.S. not sure if your changes elided the BoldFont/ItalicFont/etc. options purely for concision, or because your Font Book method obviates them, but without them, my latex can't find the proper variants, neither in the global or local case. (And the local case is basically the entire reason for OT support, because there is no global case on Overleaf.)

**Comment by fintelkai** [comment]
When you did the experiment to move the fonts to `~/Library/Fonts/` and then ran XeLaTeX, did you also move the `Extension=.otf` option to the local `\defaultfontfeatures+`? When that is active for the global case, `fontspec` couldn't find the fonts.

Eliding the BoldFont/ItalicFont/etc. options was because of this in the `lucidaot.pdf` documentation:

>In older versions of fontspec, when specifying OpenType fonts by file-name (though not with system font lookups), it was necessary to explicitly specify the italic, bold, and bold italic file names. It should no longer be necessary, but here’s the fallback code just in case you’re working with an old version [...]

So, it seems that the explicit specification is not needed in recent versions of `fontspec`. In any case, my shorter code works fine here.

**Comment by fintelkai** [comment]
Since there may not be anyone else who would like the fonts globally in the system, I can just maintain a branch for myself. But it does seem that there's a cleaner case distinction to be made, between calling the fonts by filename if there in the local source directory and calling them by font name (with spaces and all) when they've been installed via FontBook. 

Can you typeset `lucidaot-sys-example.tex` with the FontBook fonts?

**Comment by chbrown** [comment]
Ah, that works. Evidently, the `Extension=` option puts `fontspec` into "load by ﬁlename" mode. I don't entirely understand how the system font installation resolves the Bold vs. DemiBold and Italic vs. Oblique differentiation, but it _just works_.

Regarding the variants that "should no longer be necessary", were you able to get that magic to work for local fonts (i.e., without system/Font Book installation, e.g., on Overleaf)? I wasn't.

I've now got a working config with global/local support based on that `IfFileExists` check:
* I moved `Extension=.otf` inside the local-fonts condition branch
* I renamed the .otf files to match what they're called by the system
  In bash: `for font in *.otf; do mv "$font" "$(exiftool -T -FontName "$font").otf"; done`
* And renamed all the variants in the `set{main,sans,mono}font` options to match

This solution splits off less configuration into the if-local conditional branch, but over-specifies the font variants in the global (= system install) case.

The alternative would be:
* Leave the font filenames as-is.
* Move all the current (HEAD) `set{main,sans,mono,math}font` settings into the if-local branch.
* Add your `set{main,sans,mono,math}font` settings from the second message in this thread into the corresponding else branch.

Do you have a preference?

**Comment by fintelkai** [comment]
I’m fine with your solution. I don’t know that there’s an advantage to the underspecified method, other than that the doc seems to suggest the overspecification is unnecessary.

**Comment by chbrown** [comment]
If you can show me how to render with Lucida on Overleaf without explicitly specifying the `BoldFont`/`ItalicFont`/`BoldItalicFont` variants, I'd be more than happy to cut out all the overspecification :)

**Comment by fintelkai** [comment]
The `lucidaot` doc says:

> When specifying OpenType fonts by filename (though not with system font lookups), it is currently necessary to explicitly (and laboriously) specify the italic, bold, and bold italic file names. This will likely be improved in a future release of fontspec

So, for Overleaf and for anyone who has the `otf` files in a local `fonts` directory, we need the overspecification. For calling the system fonts by name, we don't. (But as I said, I don't know that there's an advantage to the underspecification.)

**Comment by fintelkai** [comment]
Actually, now I'm confused because the `lucidaot` and `lucidaot-sys` docs seem to disagree on whether the overspecification is needed when loading by filename.

**Comment by fintelkai** [comment]
I think the Lucida documentation authors were wrong when they wrote that the overspecification is not needed anymore in recent versions of `fontspec`. The most recent version of the `fontspec` doc clearly says:

>Fonts selected by filename must include bold and italic variants explicitly.

So, since we need to select by filename on Overleaf, we need the overspecification.

**Comment by fintelkai** [comment]
The `fontspec` author [states](https://github.com/wspr/fontspec/issues/314#issuecomment-343653054):

>I definitely recommend loading fonts by file name. Especially with XeTeX it makes documents more portable and means you don't have "know" the proper name of the font to load it with. The only downside is specifying italic/bold separately (in XeTeX).

**Comment by fintelkai** [comment]
So, the question is whether we want a global solution in addition to the local one and whether we want the global solution be to find the fonts by filename (and where? just somewhere in the TeX installation or also in the system fonts directories? how robust is it to search for fonts by filename in the system?).

**Comment by fintelkai** [comment]
I think on the whole I prefer a case distinction like I had working:

1. Find by filename locally, with specific italic etc. instructions. But don't call this dispreferred. That is, don't issue a warning. If someone put the font files locally, they presumably had a reason.
2. Find by font name in the system, with no specific italic etc. instructions.

**Comment by fintelkai** [comment]
I'm investigating. There are aspects to this that I still need to understand.

**Comment by fintelkai** [comment]
OK, here it is. It **is in fact possible** to have underspecified calls even if one calls the font locally by filename. What is needed is a little `fontspec` configuration file for each font family. These were actually included when I downloaded the most recent versions of the Lucida OT fonts from TUG. Here's the entire contents of `lucidabrightot.fontspec`, for example:

````latex
% Public domain, originally written 2014 by Bruno Voisin.
%
% Force lookup by filename, and define the usual variants.
% Thus, when fontspec can read this file, a document can do:
% ...
% \setmainfont{LucidaBrightOT}
% ...
% \textit{I want to be Lucida Italic!}
% ...
% And it should work as expected.  This feature was added to fontspec in
% v2.4a (2014/06/21).  The .fontspec file name itself must be
% all-lowercase in that version.
%
\defaultfontfeatures[LucidaBrightOT]
  {
    ExternalLocation,
    UprightFont = "LucidaBrightOT.otf",
    BoldFont = "LucidaBrightOT-Demi.otf",
    ItalicFont = "LucidaBrightOT-Italic.otf",
    BoldItalicFont = "LucidaBrightOT-DemiItalic.otf",
  }
````

I can put these (and maybe all the font files, which have also been upgraded) in the sp-lucida repo. And then, we can tailor `sp.cls` to that kind of installation.

**Comment by fintelkai** [comment]
Actually, @chbrown: if I send you links to the two zip archives I have (Lucida OT, and the new Lucida OT DK fonts), can you update the sp-lucida repo? I'm afraid to break something or other that you've done in there.

**Comment by chbrown** [comment]
My [lucida](https://github.com/semprag/lucida) working directory is clean and up to date with master, but sure, you can send me links / email those zips to me and I can add them. Either way.

**Comment by chbrown** [comment]
I hadn't come across such `.fontspec` config files before, but if they do the trick, cool.

The `.fontspec` solution seems preferable, but in case that doesn't work out, the following split works for local (unrenamed) font files in a `./fonts/` directory as well as global fonts installed by Font Book (but _not_ when 'installed' into a system-wide `TEXMF{HOME,LOCAL}` directory as in https://github.com/semprag/lucida#opentype):

```latex
  \defaultfontfeatures{Ligatures=TeX,Scale=0.9}
  \IfFileExists{./fonts/LucidaBrightOT.otf}{
    \ClassInfo{sp.cls}{Loading LucidaOT files from local directory (./fonts/)}
    \defaultfontfeatures+{Path=./fonts/,Extension=.otf}
    \setmainfont{LucidaBrightOT}[
      Numbers=OldStyle,
      BoldFont=*-Demi,
      ItalicFont=*-Italic,
      BoldItalicFont=*-DemiItalic]
    \setsansfont{LucidaSansOT}[
      BoldFont=*-Demi,
      ItalicFont=*-Italic,
      BoldItalicFont=*-DemiItalic]
    \setmonofont{LucidaSansTypewriterOT}[
      BoldFont=*-Bold,
      ItalicFont=*-Oblique,
      BoldItalicFont=*-BoldOblique]
    \setmathfont{LucidaBrightMathOT}
    \setmathfont{LucidaBrightMathOT-Demi}[version=bold]
  }{
    \ClassInfo{sp.cls}{Loading LucidaOT fonts from system}
    \setmainfont{Lucida Bright OT}[Numbers=OldStyle]
    \setsansfont{Lucida Sans OT}
    \setmonofont{Lucida Sans Typewriter OT}
    \setmathfont{Lucida Bright Math OT}
    \setmathfont{Lucida Bright Math OT Demibold}[version=bold]
  }
```

**Comment by fintelkai** [comment]
I'm trying the `.fontspec` thing on Overleaf now. It worked on my machine but doesn't seem to work there. Could be because they're running TexLive 2017 with `fontspec 2017/03/31 v2.6a`, while I have `fontspec-xetex 2018/07/29 vv2.6h`.

**Comment by fintelkai** [comment]
I got the following to work on Overleaf:

1. Fonts in `./fonts/` as before.
2. A `LucidaBrightOT.fontspec` file in the main directory. Note that the filename has to contain the same capitalization as the main font. (This is per the `fontspec` documentation, and contra the LucidaOT distribution (which has lowercase in the file name, which does work locally for me for some reason)). It has the following content:

````latex
\defaultfontfeatures[LucidaBrightOT]
  {
    Path=./fonts/,
    UprightFont = "LucidaBrightOT.otf",
    BoldFont = "LucidaBrightOT-Demi.otf",
    ItalicFont = "LucidaBrightOT-Italic.otf",
    BoldItalicFont = "LucidaBrightOT-DemiItalic.otf",
  }
````
3. A test file with this preamble, which contains no variant specification:

````latex
\documentclass{article}
\usepackage{fontspec}
\usepackage{unicode-math}

\defaultfontfeatures{Scale=.92,Path=./fonts/}
\setmainfont[Ligatures=TeX]{LucidaBrightOT}
\setsansfont[Ligatures=TeX]{LucidaSansOT}
\setmonofont{LucidaSansTypewriterOT}
\setmathfont{LucidaBrightMathOT}

\begin{document}
````

**Comment by chbrown** [comment]
Finally getting around to trying out the `*.fontspec` approach...

@fintelkai I'm not sure how your latest comment substantially differs from [the configuration I'd been using on Overleaf](https://github.com/semprag/overleaf#instructions) as of eb22a19, with f3f8ab9 adding support for `TEXMFHOME`-based (global-, but not system-) installation of OpenType fonts. The test file in your item 3. won't render with system-installed fonts, even if you remove the `Path=./fonts/` setting, will it? (Your earlier [comment](https://github.com/semprag/tex/issues/20#issuecomment-414338577) suggested that the font names were the crux of the discrepancy.)

The original point of this issue (#20) was to support loading OpenType Lucida (via `[lucidaot]`) from the system-installed fonts as well as from files in `./fonts/` (for Overleaf) with no (or minimal?) changes to the document source file, right?

If so, it seems to me that the starting point is to share the following `fontspec` package configuration between local/system...
```tex
\defaultfontfeatures{Ligatures=TeX,Scale=0.9}
\setmainfont{Lucida Bright OT}[Numbers=OldStyle]
\setsansfont{Lucida Sans OT}
\setmonofont{Lucida Sans Typewriter OT}
\setmathfont{Lucida Bright Math OT}
```
...and then customize the _local_ case as needed, because it doesn't seem to be possible to customize the _system_ config beyond the names supplied in the `\setmainfont{...}`, etc., commands.

1. The first problem I'm encountering is that the `fontspec` package doesn't seem to locate the `<FontName>.fontspec` file if it contains spaces. I put a `Lucida Bright OT.fontspec` in the same folder as my `.tex` document — nothing. I copied it to `./fonts/Lucida Bright OT.fontspec` — nothing. (If I change `sp.cls` to specify the font name without spaces, `\setmainfont{LucidaBrightOT}[...]`, and rename the file to `LucidaBrightOT.fontspec`, then I can see from the `XeTeX` log that it reads the file, although it complains that the `UprightFont` key "is unknown and is being ignored", though that seems to be a different problem.)
2. Second, the `.fontspec` files seem to be plain LaTeX sources that `fontspec` conditionally looks for when it loads a font. I'm not sure what the advantage they confer vs. putting the same configuration directly in the `\IfFileExists{./fonts/...}` branch in `sp.cls` (as in my previous comment in this thread). If the idea is that they are provided by the official Lucida distribution, and thus canonical, this seems to be defeated by having to rename them and put them in just the right place, as well as change the optional argument from `[LucidaBrightOT]` to `[Lucida Bright OT]` and replace the deprecated `ExternalLocation` with a specific `Path=...` setting.

Nevertheless, I'm about to commit a fix taking a different approach, somewhere in the middle between my previous comment and how the `.fontspec` files work. This succeeds in all significant cases: 1) Overleaf with fonts in `./fonts/*.otf`, 2) Local XeLaTeX with fonts in `./fonts/*.otf`, and 3) Local XeLaTeX with the OpenType fonts installed by Font Book.

Let me know if you encounter any issues.
